### PR TITLE
Adds user save file feature

### PR DESCRIPTION
**Pull request by christianarab**

### CODE REVIEW

**Comment by ogryzek** [comment]
Looks pretty good, @christianarab! I'd love to see some tests that support the functionality. Also, I see there's a `Player.create_user`, which I find to be interesting naming.

Is there a difference between Player and User? If not, perhaps consider `Player.create` as a class method that instantiates a new Player `Player.new` and _creates_ it by saving the data `@player.save`.

Could you perhaps explain some of the logic as well? I see that the `Player` class is responsible for creating instances of the `Cat` class, with `Player.create_cat` and then that a saved item in the `players` data file has cat data, e.g.

```
["Player=name: meowmaster, size: medium, energy: 100, agility: 75, strength: 75, confidence: 50, wins: 0, losses: 0"]
```

---

A couple of suggests are that you may consider having `Player` and `Cat` instantiate independently, i.e. `Player` is _not_ responsible for instantiating instances of `Cat` objects. If that's the case, then there may be a different way to represent the `Player`/`Cat` relationship.  
 
One idea would be that you could have something like the following:

```ruby 
@player.cats # returns a list of Cat objects that belong to the player

@cat.belongs_to(@player) # assigns a Player object as the owner of a @cat object
```
  
The main game loop could require a "user" (someone who is using the application) to either select an existing `Player` or create a new `Player`. Once a `Player` has been selected or created, it can ask whether there is another player, or if there will be an automated opponent (a computer character).
  
Q: will that computer character be a randomly generated character, will it be selected from the set, or a sub-set of existing Player characters, does the program have its own list of Player character to choose from, or...?  
  
The players can then enter into a competition. During a competition, `@player.cats` compete, or rather a `Cat` object (`@cat`) that belongs to a `Player` that has entered into a competition will be competing. A `@cat` has attributes such as energy, agility, etc. and they can help determine whether the cat will will or lose, however the `@player` should be the one who will be awarded points or whatever other prize(s) your application supports.  
  
OK, that's a little food for thought. Let me know if you'd like to hop into a screenshare or chat about design decisions for how your game loop functions or what sorts of objects interact and how.

**Comment by christianarab** [comment]
Hello Drew. Thank your for the helpful comments. These decisions between Player(/User which I will fix convention), instating a new Cat, saving the data are what I am seeing as a severe weakness.

 With the requirements , I would like an experience where:
- The Player(s) can have a profile
- The Player(s) can store to have a cat, and its traits, points, etc. in persisted memory
- The Player (s) can play against a dummy profile/computer

At the moment, the logic that I currently have is interested with saving both the name of the player, and their cat with trait values. I wanted Player to instate a cat into memory, and then into a file by line. I want to be able to load this info - as class Player and Cat data - manipulate it and push it back.  I find that it has already become tied strands of spaghetti for how the instances will be used in the game feature. With your suggestions I will attempt to build the classes with more independent logic.

The question about the computer is a good one. My inclination was to create a new instance of Player and assign it a name that denotes that it is a computer. The game features I have don't seem highly interactive or turned based so having a dummy profile to start might be an option. I think I can perhaps save some dummy profiles in a separate file and 'load' it in. I can also see myself implementing sub-sets of these profiles, with different trait categories that can change the "difficulty" of winning.

I had an editing job this Saturday that I am balancing but I will get back to the code later today. Will push code as I write.
Perhaps tomorrow if you have time for a screen share I would gladly take it up!

**Comment by ogryzek** [comment]
> *  The Player(s) can have a profile

What is a _profile_? Is this something _different_ from `Player`?  
  
>  I wanted Player to instate a cat into memory, and then into a file by line.

_Why_? That is, why should Player be concerned with the specifics of how `@cat` data is _saved_?  
  
Some suggestions to consider:  
  
A `@player` can have many cats. So, you might have something like `@player.cats` which returns a list of `@cat` objects that belong to the player.

If you imagine how `@cats` (a list/Array) of `@cat` objects is instantiated, you might think that the `Cat` class is responsible for reading the data and returning a list of cats that belong to a `player`. How might that work?  
  
We implemented a [`find_by_email`](https://github.com/compsciacademy/fulltime-program-2021-Q2/blob/main/Week02/Day09/users/user.rb#L52-L63) method on the `User` class the other day. Perhaps `Cat` objects could have a `belongs_to` attribute that lets you know which `User` they belong to, or _if_ they belong to a user.  
  
> The question about the computer is a good one. My inclination was to create a new instance of Player and assign it a name that denotes that it is a computer. The game features I have don't seem highly interactive or turned based so having a dummy profile to start might be an option. I think I can perhaps save some dummy profiles in a separate file and 'load' it in. I can also see myself implementing sub-sets of these profiles, with different trait categories that can change the "difficulty" of winning.  
  
OK, let's see where this goes.

> I had an editing job this Saturday that I am balancing but I will get back to the code later today. Will push code as I write.
Perhaps tomorrow if you have time for a screen share I would gladly take it up!

Let me know.

**Comment by christianarab** [comment]
What is a profile? Is this something different from Player?

- I wanted to somehow work the Player class contain to contain a name, and the cat. I used the term profile, in a sense of perhaps saving "profiles" of players.

Why? That is, why should Player be concerned with the specifics of how @cat data is saved?

- After your suggestions I now believe that it shouldn't. My direction was that of a novice. 

I will e-mail you about tomorrow!

**Pull request merged**
